// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Infrastructure.Persistence;

#nullable disable

namespace Portfolio.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260407173735_update2")]
    partial class update2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Portfolio.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("_expiryDate")
                        .HasColumnType("date")
                        .HasColumnName("ExpiryDate");

                    b.Property<DateOnly>("_issueDate")
                        .HasColumnType("date")
                        .HasColumnName("IssueDate");

                    b.Property<string>("_issuingOrganization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("IssuingOrganization");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("IX_Certifications_PortfolioId");

                    b.ToTable("Certifications", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Portfolio.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Company");

                    b.Property<string>("_description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("_role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("IX_Experiences_PortfolioId");

                    b.ToTable("Experiences", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Portfolio.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("_activeServicesCount")
                        .HasColumnType("int")
                        .HasColumnName("ActiveServicesCount");

                    b.Property<Guid>("_ownerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerId");

                    b.Property<string>("_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Review.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Comment");

                    b.Property<Guid>("_reviewerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReviewerId");

                    b.Property<Guid>("_serviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ServiceId");

                    b.Property<string>("_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("_serviceId")
                        .HasDatabaseName("IX_Reviews_ServiceId");

                    b.HasIndex("_serviceId", "_reviewerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Reviews_ServiceId_ReviewerId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<DateOnly>("_issuedAt")
                        .HasColumnType("date")
                        .HasColumnName("IssuedAt");

                    b.Property<string>("_issuedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("IssuedBy");

                    b.Property<string>("_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_Awards_ServiceId");

                    b.ToTable("Service_Awards", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Answer");

                    b.Property<string>("_question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Question");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_Faqs_ServiceId");

                    b.ToTable("Service_Faqs", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.ImageUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ImageUrls_ServiceId");

                    b.ToTable("Service_ImageUrls", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Description");

                    b.Property<Guid>("_portfolioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PortfolioId");

                    b.Property<string>("_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("_portfolioId")
                        .HasDatabaseName("IX_Services_PortfolioId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_Tags_ServiceId");

                    b.ToTable("Service_Tags", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Portfolio.Entities.Certification", b =>
                {
                    b.HasOne("Portfolio.Domain.Aggregates.Portfolio.Entities.Portfolio", null)
                        .WithMany("_certifications")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Url", "_credentialUrl", b1 =>
                        {
                            b1.Property<Guid>("CertificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("CredentialUrl");

                            b1.HasKey("CertificationId");

                            b1.ToTable("Certifications");

                            b1.WithOwner()
                                .HasForeignKey("CertificationId");
                        });

                    b.Navigation("_credentialUrl");
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Portfolio.Entities.Experience", b =>
                {
                    b.HasOne("Portfolio.Domain.Aggregates.Portfolio.Entities.Portfolio", null)
                        .WithMany("_experiences")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.DateRange", "_period", b1 =>
                        {
                            b1.Property<Guid>("ExperienceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly?>("End")
                                .HasColumnType("date")
                                .HasColumnName("EndDate");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("StartDate");

                            b1.HasKey("ExperienceId");

                            b1.ToTable("Experiences");

                            b1.WithOwner()
                                .HasForeignKey("ExperienceId");
                        });

                    b.Navigation("_period");
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Portfolio.Entities.Portfolio", b =>
                {
                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.Entities.ContactInfo", "_contactInfo", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("Portfolio_ContactInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");

                            b1.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Url", "Website", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoPortfolioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("nvarchar(300)")
                                        .HasColumnName("Website");

                                    b2.HasKey("ContactInfoPortfolioId");

                                    b2.ToTable("Portfolio_ContactInfos");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPortfolioId");
                                });

                            b1.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoPortfolioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("Email");

                                    b2.HasKey("ContactInfoPortfolioId");

                                    b2.ToTable("Portfolio_ContactInfos");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPortfolioId");
                                });

                            b1.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.PhoneNumber", "Phone", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoPortfolioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Phone");

                                    b2.HasKey("ContactInfoPortfolioId");

                                    b2.ToTable("Portfolio_ContactInfos");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPortfolioId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("Phone");

                            b1.Navigation("Website");
                        });

                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.Entities.GeneralInfo", "_generalInfo", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Bio")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("Portfolio_GeneralInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");

                            b1.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Url", "AvatarUrl", b2 =>
                                {
                                    b2.Property<Guid>("GeneralInfoPortfolioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("AvatarUrl");

                                    b2.HasKey("GeneralInfoPortfolioId");

                                    b2.ToTable("Portfolio_GeneralInfos");

                                    b2.WithOwner()
                                        .HasForeignKey("GeneralInfoPortfolioId");
                                });

                            b1.Navigation("AvatarUrl");
                        });

                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.Entities.LocationInfo", "_locationInfo", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Timezone")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("Portfolio_LocationInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");
                        });

                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.Entities.ProfessionalInfo", "_professionalInfo", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Headline")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("Portfolio_ProfessionalInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");

                            b1.OwnsMany("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Skill", "_skills", b2 =>
                                {
                                    b2.Property<Guid>("PortfolioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Level")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.HasKey("PortfolioId", "Id");

                                    b2.ToTable("Portfolio_Skills", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PortfolioId");
                                });

                            b1.Navigation("_skills");
                        });

                    b.OwnsMany("Portfolio.Domain.Aggregates.Portfolio.ValueObject.SocialLink", "_socialLinks", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("PortfolioId", "Id");

                            b1.ToTable("Portfolio_SocialLinks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");

                            b1.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Url", "Url", b2 =>
                                {
                                    b2.Property<Guid>("SocialLinkPortfolioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("SocialLinkId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("Url");

                                    b2.HasKey("SocialLinkPortfolioId", "SocialLinkId");

                                    b2.ToTable("Portfolio_SocialLinks");

                                    b2.WithOwner()
                                        .HasForeignKey("SocialLinkPortfolioId", "SocialLinkId");
                                });

                            b1.Navigation("Url")
                                .IsRequired();
                        });

                    b.Navigation("_contactInfo");

                    b.Navigation("_generalInfo");

                    b.Navigation("_locationInfo");

                    b.Navigation("_professionalInfo");

                    b.Navigation("_socialLinks");
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Review.Review", b =>
                {
                    b.OwnsOne("Portfolio.Domain.Aggregates.Review.Rating", "_rating", b1 =>
                        {
                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Rating");

                            b1.HasKey("ReviewId");

                            b1.ToTable("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId");
                        });

                    b.Navigation("_rating");
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.Award", b =>
                {
                    b.HasOne("Portfolio.Domain.Aggregates.Service.Entities.Service", null)
                        .WithMany("_awards")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.FAQ", b =>
                {
                    b.HasOne("Portfolio.Domain.Aggregates.Service.Entities.Service", null)
                        .WithMany("_faqs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.ImageUrl", b =>
                {
                    b.HasOne("Portfolio.Domain.Aggregates.Service.Entities.Service", null)
                        .WithMany("_imageUrls")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Url", "_value", b1 =>
                        {
                            b1.Property<Guid>("ImageUrlId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Url");

                            b1.HasKey("ImageUrlId");

                            b1.ToTable("Service_ImageUrls");

                            b1.WithOwner()
                                .HasForeignKey("ImageUrlId");
                        });

                    b.Navigation("_value");
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.Service", b =>
                {
                    b.OwnsOne("Portfolio.Domain.Aggregates.Portfolio.ValueObject.Url", "_coverImageUrl", b1 =>
                        {
                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("CoverImageUrl");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("Portfolio.Domain.Aggregates.Service.ValueObject.Pricing", "_pricing", b1 =>
                        {
                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Pricing_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Pricing_Currency");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Pricing_Type");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("_coverImageUrl");

                    b.Navigation("_pricing");
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.Tag", b =>
                {
                    b.HasOne("Portfolio.Domain.Aggregates.Service.Entities.Service", null)
                        .WithMany("_tags")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Portfolio.Entities.Portfolio", b =>
                {
                    b.Navigation("_certifications");

                    b.Navigation("_experiences");
                });

            modelBuilder.Entity("Portfolio.Domain.Aggregates.Service.Entities.Service", b =>
                {
                    b.Navigation("_awards");

                    b.Navigation("_faqs");

                    b.Navigation("_imageUrls");

                    b.Navigation("_tags");
                });
#pragma warning restore 612, 618
        }
    }
}
