<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\Aggregates\Portfolio\Enums\" />
    <Folder Include="Domain\Aggregates\Portfolio\Repositories\" />
    <Folder Include="Infrastructure\Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConnectPro.Identity\Identity.csproj" />
    <ProjectReference Include="..\ConnectPro.SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\EXAUCE\Desktop\ConnectProBackend\ConnectPro.Portfolio\Application\Reviews\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\EXAUCE\Desktop\ConnectProBackend\ConnectPro.Portfolio\Application\Reviews\.editorconfig" />
  </ItemGroup>

</Project>
